<?php


///
$datalist['countries'] = array(
        'AF' => _('Afghanistan'),
        'AL' => _('Albania'),
        'DZ' => _('Algeria'),
        'AS' => _('American Samoa'),
        'AD' => _('Andorra'),
        'AO' => _('Angola'),
        'AI' => _('Anguilla'),
        'AQ' => _('Antarctica'),
        'AG' => _('Antigua and Barbuda'),
        'AR' => _('Argentina'),
        'AM' => _('Armenia'),
        'AW' => _('Aruba'),
        'AU' => _('Australia'),
        'AT' => _('Austria'),
        'AZ' => _('Azerbaijan'),
        'BS' => _('Bahamas'),
        'BH' => _('Bahrain'),
        'BD' => _('Bangladesh'),
        'BB' => _('Barbados'),
        'BY' => _('Belarus'),
        'BE' => _('Belgium'),
        'BZ' => _('Belize'),
        'BJ' => _('Benin'),
        'BM' => _('Bermuda'),
        'BT' => _('Bhutan'),
        'BO' => _('Bolivia'),
        'BA' => _('Bosnia and Herzegovina'),
        'BW' => _('Botswana'),
        'BV' => _('Bouvet Island'),
        'BR' => _('Brazil'),
        'BQ' => _('British Antarctic Territory'),
        'IO' => _('British Indian Ocean Territory'),
        'VG' => _('British Virgin Islands'),
        'BN' => _('Brunei'),
        'BG' => _('Bulgaria'),
        'BF' => _('Burkina Faso'),
        'BI' => _('Burundi'),
        'KH' => _('Cambodia'),
        'CM' => _('Cameroon'),
        'CA' => _('Canada'),
        'CT' => _('Canton and Enderbury Islands'),
        'CV' => _('Cape Verde'),
        'KY' => _('Cayman Islands'),
        'CF' => _('Central African Republic'),
        'TD' => _('Chad'),
        'CL' => _('Chile'),
        'CN' => _('China'),
        'CX' => _('Christmas Island'),
        'CC' => _('Cocos [Keeling] Islands'),
        'CO' => _('Colombia'),
        'KM' => _('Comoros'),
        'CG' => _('Congo - Brazzaville'),
        'CD' => _('Congo - Kinshasa'),
        'CK' => _('Cook Islands'),
        'CR' => _('Costa Rica'),
        'HR' => _('Croatia'),
        'CU' => _('Cuba'),
        'CY' => _('Cyprus'),
        'CZ' => _('Czech Republic'),
        'CI' => _('Côte d’Ivoire'),
        'DK' => _('Denmark'),
        'DJ' => _('Djibouti'),
        'DM' => _('Dominica'),
        'DO' => _('Dominican Republic'),
        'NQ' => _('Dronning Maud Land'),
        'DD' => _('East Germany'),
        'EC' => _('Ecuador'),
        'EG' => _('Egypt'),
        'SV' => _('El Salvador'),
        'GQ' => _('Equatorial Guinea'),
        'ER' => _('Eritrea'),
        'EE' => _('Estonia'),
        'ET' => _('Ethiopia'),
        'FK' => _('Falkland Islands'),
        'FO' => _('Faroe Islands'),
        'FJ' => _('Fiji'),
        'FI' => _('Finland'),
        'FR' => _('France'),
        'GF' => _('French Guiana'),
        'PF' => _('French Polynesia'),
        'TF' => _('French Southern Territories'),
        'FQ' => _('French Southern and Antarctic Territories'),
        'GA' => _('Gabon'),
        'GM' => _('Gambia'),
        'GE' => _('Georgia'),
        'DE' => _('Germany'),
        'GH' => _('Ghana'),
        'GI' => _('Gibraltar'),
        'GR' => _('Greece'),
        'GL' => _('Greenland'),
        'GD' => _('Grenada'),
        'GP' => _('Guadeloupe'),
        'GU' => _('Guam'),
        'GT' => _('Guatemala'),
        'GG' => _('Guernsey'),
        'GN' => _('Guinea'),
        'GW' => _('Guinea-Bissau'),
        'GY' => _('Guyana'),
        'HT' => _('Haiti'),
        'HM' => _('Heard Island and McDonald Islands'),
        'HN' => _('Honduras'),
        'HK' => _('Hong Kong SAR China'),
        'HU' => _('Hungary'),
        'IS' => _('Iceland'),
        'IN' => _('India'),
        'ID' => _('Indonesia'),
        'IR' => _('Iran'),
        'IQ' => _('Iraq'),
        'IE' => _('Ireland'),
        'IM' => _('Isle of Man'),
        'IL' => _('Israel'),
        'IT' => _('Italy'),
        'JM' => _('Jamaica'),
        'JP' => _('Japan'),
        'JE' => _('Jersey'),
        'JT' => _('Johnston Island'),
        'JO' => _('Jordan'),
        'KZ' => _('Kazakhstan'),
        'KE' => _('Kenya'),
        'KI' => _('Kiribati'),
        'KW' => _('Kuwait'),
        'KG' => _('Kyrgyzstan'),
        'LA' => _('Laos'),
        'LV' => _('Latvia'),
        'LB' => _('Lebanon'),
        'LS' => _('Lesotho'),
        'LR' => _('Liberia'),
        'LY' => _('Libya'),
        'LI' => _('Liechtenstein'),
        'LT' => _('Lithuania'),
        'LU' => _('Luxembourg'),
        'MO' => _('Macau SAR China'),
        'MK' => _('Macedonia'),
        'MG' => _('Madagascar'),
        'MW' => _('Malawi'),
        'MY' => _('Malaysia'),
        'MV' => _('Maldives'),
        'ML' => _('Mali'),
        'MT' => _('Malta'),
        'MH' => _('Marshall Islands'),
        'MQ' => _('Martinique'),
        'MR' => _('Mauritania'),
        'MU' => _('Mauritius'),
        'YT' => _('Mayotte'),
        'FX' => _('Metropolitan France'),
        'MX' => _('Mexico'),
        'FM' => _('Micronesia'),
        'MI' => _('Midway Islands'),
        'MD' => _('Moldova'),
        'MC' => _('Monaco'),
        'MN' => _('Mongolia'),
        'ME' => _('Montenegro'),
        'MS' => _('Montserrat'),
        'MA' => _('Morocco'),
        'MZ' => _('Mozambique'),
        'MM' => _('Myanmar [Burma]'),
        'NA' => _('Namibia'),
        'NR' => _('Nauru'),
        'NP' => _('Nepal'),
        'NL' => _('Netherlands'),
        'AN' => _('Netherlands Antilles'),
        'NT' => _('Neutral Zone'),
        'NC' => _('New Caledonia'),
        'NZ' => _('New Zealand'),
        'NI' => _('Nicaragua'),
        'NE' => _('Niger'),
        'NG' => _('Nigeria'),
        'NU' => _('Niue'),
        'NF' => _('Norfolk Island'),
        'KP' => _('North Korea'),
        'VD' => _('North Vietnam'),
        'MP' => _('Northern Mariana Islands'),
        'NO' => _('Norway'),
        'OM' => _('Oman'),
        'PC' => _('Pacific Islands Trust Territory'),
        'PK' => _('Pakistan'),
        'PW' => _('Palau'),
        'PS' => _('Palestinian Territories'),
        'PA' => _('Panama'),
        'PZ' => _('Panama Canal Zone'),
        'PG' => _('Papua New Guinea'),
        'PY' => _('Paraguay'),
        'YD' => _('People\'s Democratic Republic of Yemen'),
        'PE' => _('Peru'),
        'PH' => _('Philippines'),
        'PN' => _('Pitcairn Islands'),
        'PL' => _('Poland'),
        'PT' => _('Portugal'),
        'PR' => _('Puerto Rico'),
        'QA' => _('Qatar'),
        'RO' => _('Romania'),
        'RU' => _('Russia'),
        'RW' => _('Rwanda'),
        'RE' => _('Réunion'),
        'BL' => _('Saint Barthélemy'),
        'SH' => _('Saint Helena'),
        'KN' => _('Saint Kitts and Nevis'),
        'LC' => _('Saint Lucia'),
        'MF' => _('Saint Martin'),
        'PM' => _('Saint Pierre and Miquelon'),
        'VC' => _('Saint Vincent and the Grenadines'),
        'WS' => _('Samoa'),
        'SM' => _('San Marino'),
        'SA' => _('Saudi Arabia'),
        'SN' => _('Senegal'),
        'RS' => _('Serbia'),
        'CS' => _('Serbia and Montenegro'),
        'SC' => _('Seychelles'),
        'SL' => _('Sierra Leone'),
        'SG' => _('Singapore'),
        'SK' => _('Slovakia'),
        'SI' => _('Slovenia'),
        'SB' => _('Solomon Islands'),
        'SO' => _('Somalia'),
        'ZA' => _('South Africa'),
        'GS' => _('South Georgia and the South Sandwich Islands'),
        'KR' => _('South Korea'),
        'ES' => _('Spain'),
        'LK' => _('Sri Lanka'),
        'SD' => _('Sudan'),
        'SR' => _('Suriname'),
        'SJ' => _('Svalbard and Jan Mayen'),
        'SZ' => _('Swaziland'),
        'SE' => _('Sweden'),
        'CH' => _('Switzerland'),
        'SY' => _('Syria'),
        'ST' => _('São Tomé and Príncipe'),
        'TW' => _('Taiwan'),
        'TJ' => _('Tajikistan'),
        'TZ' => _('Tanzania'),
        'TH' => _('Thailand'),
        'TL' => _('Timor-Leste'),
        'TG' => _('Togo'),
        'TK' => _('Tokelau'),
        'TO' => _('Tonga'),
        'TT' => _('Trinidad and Tobago'),
        'TN' => _('Tunisia'),
        'TR' => _('Turkey'),
        'TM' => _('Turkmenistan'),
        'TC' => _('Turks and Caicos Islands'),
        'TV' => _('Tuvalu'),
        'UM' => _('U.S. Minor Ouexampleying Islands'),
        'PU' => _('U.S. Miscellaneous Pacific Islands'),
        'VI' => _('U.S. Virgin Islands'),
        'UG' => _('Uganda'),
        'UA' => _('Ukraine'),
        'SU' => _('Union of Soviet Socialist Republics'),
        'AE' => _('United Arab Emirates'),
        'GB' => _('United Kingdom'),
        'US' => _('United States'),
        'ZZ' => _('Unknown or Invalid Region'),
        'UY' => _('Uruguay'),
        'UZ' => _('Uzbekistan'),
        'VU' => _('Vanuatu'),
        'VA' => _('Vatican City'),
        'VE' => _('Venezuela'),
        'VN' => _('Vietnam'),
        'WK' => _('Wake Island'),
        'WF' => _('Wallis and Futuna'),
        'EH' => _('Western Sahara'),
        'YE' => _('Yemen'),
        'ZM' => _('Zambia'),
        'ZW' => _('Zimbabwe'),
        'AX' => _('Åland Islands'),
);
///
/////////////////////////
$datalist['languages'] = array(
            'af-ZA' => 'Afrikaans - South Africa', 'sq-AL' => 'Albanian - Albania', 'ar-DZ' => 'Arabic - Algeria',
            'ar-BH' => 'Arabic - Bahrain', 'ar-EG' => 'Arabic - Egypt', 'ar-IQ' => 'Arabic - Iraq',
            'ar-JO' => 'Arabic - Jordan', 'ar-KW' => 'Arabic - Kuwait', 'ar-LB' => 'Arabic - Lebanon',
            'ar-LY' => 'Arabic - Libya', 'ar-MA' => 'Arabic - Morocco',
            'ar-OM' => 'Arabic - Oman', 'ar-QA' => 'Arabic - Qatar', 'ar-SA' => 'Arabic - Saudi Arabia',
            'ar-SY' => 'Arabic - Syria', 'ar-TN' => 'Arabic - Tunisia', 'ar-AE' => 'Arabic - United Arab Emirates',
            'ar-YE' => 'Arabic - Yemen', 'hy-AM' => 'Armenian - Armenia', 'Cy-az-AZ' => 'Azeri (Cyrillic) - Azerbaijan',
            'Lt-az-AZ' => 'Azeri (Latin) - Azerbaijan', 'eu-ES' => 'Basque - Basque', 'be-BY' => 'Belarusian - Belarus',
            'bg-BG' => 'Bulgarian - Bulgaria', 'ca-ES' => 'Catalan - Catalan',
            'zh-CN' => 'Chinese - China', 'zh-HK' => 'Chinese - Hong Kong SAR', 'zh-MO' => 'Chinese - Macau SAR',
            'zh-SG' => 'Chinese - Singapore', 'zh-TW' => 'Chinese - Taiwan', 'zh-CHS' => 'Chinese (Simplified)',
            'zh-CHT' => 'Chinese (Traditional)', 'hr-HR' => 'Croatian - Croatia', 'cs-CZ' => 'Czech - Czech Republic',
            'da-DK' => 'Danish - Denmark', 'div-MV' => 'Dhivehi - Maldives', 'nl-BE' => 'Dutch - Belgium',
            'nl-NL' => 'Dutch - The Netherlands', 'en-AU' => 'English - Australia', 'en-BZ' => 'English - Belize',
            'en-CA' => 'English - Canada', 'en-CB' => 'English - Caribbean', 'en-IE' => 'English - Ireland',
            'en-JM' => 'English - Jamaica', 'en-NZ' => 'English - New Zealand', 'en-PH' => 'English - Philippines',
            'en-ZA' => 'English - South Africa', 'en-TT' => 'English - Trinidad and Tobago', 'en-GB' => 'English - United Kingdom',
            'en-US' => 'English - United States', 'en-ZW' => 'English - Zimbabwe', 'et-EE' => 'Estonian - Estonia',
            'fo-FO' => 'Faroese - Faroe Islands', 'fa-IR' => 'Farsi - Iran', 'fi-FI' => 'Finnish - Finland',
            'fr-BE' => 'French - Belgium', 'fr-CA' => 'French - Canada', 'fr-FR' => 'French - France',
            'fr-LU' => 'French - Luxembourg', 'fr-MC' => 'French - Monaco', 'fr-CH' => 'French - Switzerland',
            'gl-ES' => 'Galician - Galician', 'ka-GE' => 'Georgian - Georgia', 'de-AT' => 'German - Austria',
            'de-DE' => 'German - Germany', 'de-LI' => 'German - Liechtenstein', 'de-LU' => 'German - Luxembourg',
            'de-CH' => 'German - Switzerland', 'el-GR' => 'Greek - Greece', 'gu-IN' => 'Gujarati - India',
            'he-IL' => 'Hebrew - Israel', 'hi-IN' => 'Hindi - India', 'hu-HU' => 'Hungarian - Hungary',
            'is-IS' => 'Icelandic - Iceland', 'id-ID' => 'Indonesian - Indonesia', 'it-IT' => 'Italian - Italy',
            'it-CH' => 'Italian - Switzerland', 'ja-JP' => 'Japanese - Japan', 'kn-IN' => 'Kannada - India',
            'kk-KZ' => 'Kazakh - Kazakhstan', 'kok-IN' => 'Konkani - India', 'ko-KR' => 'Korean - Korea',
            'ky-KZ' => 'Kyrgyz - Kazakhstan', 'lv-LV' => 'Latvian - Latvia', 'lt-LT' => 'Lithuanian - Lithuania',
            'mk-MK' => 'Macedonian (FYROM)', 'ms-BN' => 'Malay - Brunei', 'ms-MY' => 'Malay - Malaysia',
            'mr-IN' => 'Marathi - India', 'mn-MN' => 'Mongolian - Mongolia', 'nb-NO' => 'Norwegian (Bokmål) - Norway',
            'nn-NO' => 'Norwegian (Nynorsk) - Norway', 'pl-PL' => 'Polish - Poland', 'pt-BR' => 'Portuguese - Brazil',
            'pt-PT' => 'Portuguese - Portugal', 'pa-IN' => 'Punjabi - India', 'ro-RO' => 'Romanian - Romania',
            'ru-RU' => 'Russian - Russia', 'sa-IN' => 'Sanskrit - India', 'Cy-sr-SP' => 'Serbian (Cyrillic) - Serbia',
            'Lt-sr-SP' => 'Serbian (Latin) - Serbia', 'sk-SK' => 'Slovak - Slovakia', 'sl-SI' => 'Slovenian - Slovenia',
            'es-AR' => 'Spanish - Argentina', 'es-BO' => 'Spanish - Bolivia', 'es-CL' => 'Spanish - Chile',
            'es-CO' => 'Spanish - Colombia', 'es-CR' => 'Spanish - Costa Rica', 'es-DO' => 'Spanish - Dominican Republic',
            'es-EC' => 'Spanish - Ecuador', 'es-SV' => 'Spanish - El Salvador', 'es-GT' => 'Spanish - Guatemala',
            'es-HN' => 'Spanish - Honduras', 'es-MX' => 'Spanish - Mexico', 'es-NI' => 'Spanish - Nicaragua',
            'es-PA' => 'Spanish - Panama', 'es-PY' => 'Spanish - Paraguay', 'es-PE' => 'Spanish - Peru',
            'es-PR' => 'Spanish - Puerto Rico', 'es-ES' => 'Spanish - Spain', 'es-UY' => 'Spanish - Uruguay',
            'es-VE' => 'Spanish - Venezuela', 'sw-KE' => 'Swahili - Kenya', 'sv-FI' => 'Swedish - Finland', 'sv-SE' => 'Swedish - Sweden',
            'syr-SY' => 'Syriac - Syria', 'ta-IN' => 'Tamil - India', 'tt-RU' => 'Tatar - Russia', 'te-IN' => 'Telugu - India',
            'th-TH' => 'Thai - Thailand', 'tr-TR' => 'Turkish - Turkey', 'uk-UA' => 'Ukrainian - Ukraine', 'ur-PK' => 'Urdu - Pakistan',
            'Cy-uz-UZ' => 'Uzbek (Cyrillic) - Uzbekistan', 'Lt-uz-UZ' => 'Uzbek (Latin) - Uzbekistan', 'vi-VN' => 'Vietnamese - Vietnam'
);
//////////////////////
